%YAML:1.0


cam0:
  T_cam_imu:
    - [0.9998265105702439, 0.007720561164568957, 0.016951156191702683, 0.01976500899286784]
    - [-0.00776336756203289, 0.9999668364285761, 0.002460928102039484, 0.004081894822315071]
    - [-0.01693159428489019, -0.0025920992131440064, 0.9998532903064541, -0.04396709472558018]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [0.0737857621289457, -0.1569990377710313, -0.0048554040005669334, -0.00046976202674121523]
  distortion_model: radtan
  intrinsics: [875.6072902651862, 875.6905194005133, 630.2848301047758, 348.57063388737987]
  resolution: [1280, 720]
  rostopic: /camera/camera/color/image_raw
  timeshift_cam_imu: 0.002524377913673846